### ISSUE TITLE
Unhandled Exception when importing a 403 url

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#104]
Swifty 2.1.1.1

![image](https://cloud.githubusercontent.com/assets/1235520/11766944/5dd9bda4-a19c-11e5-9af1-5009bc305362.png)

```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at SwiftUpdater.Pages.RepoSettings.ImportTryButton_Click(Object sender, EventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\RepoSettings.cs:line 323
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)```

**Comment by headswe** [comment]
Thanks!

**Comment by headswe** [comment]
Fixed.

**Comment by bux578** [comment]
Any other HTTP status codes that could need a separate error handling?
