### ISSUE TITLE
Unhandled Exception when pressing play

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#105]
2.1.1.1

![image](https://cloud.githubusercontent.com/assets/1235520/11768317/705e523c-a1c9-11e5-8be4-b7290887ed4e.png)

Last few Swifty.log entries
```2015-12-13 18:42:56,496 [1] INFO SwiftUpdater.Program - Checking for URL Protocol
2015-12-13 18:42:56,497 [1] INFO SwiftUpdater.Program - Checking for URL message
2015-12-13 18:42:56,497 [1] INFO SwiftUpdater.Settings - Attempting to load settings file
2015-12-13 18:42:56,497 [1] INFO SwiftUpdater.Settings - Loading settings file
2015-12-13 18:42:56,545 [1] INFO SwiftUpdater.Pages.RepoView - Repoview shown
2015-12-13 18:42:56,546 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
2015-12-13 18:42:56,592 [1] INFO SwiftUpdater.Pages.Main - MainView Shown
2015-12-13 18:44:24,778 [1] INFO SwiftUpdater.Pages.RepoSettings - Editing repo```
Sorry, I really can't give you any repro steps.
Randomly happened after launching Swifty and pressing "Join".

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Repository.GetFolder(String currentAddon) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Settings.cs:line 100
   at SwiftUpdater.Controls.NewRepoBox.PlayButton_Click(Object sender, EventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Controls\NewRepoBox.cs:line 203
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by headswe** [comment]
Thanks man

2015-12-13 18:45 GMT+01:00 bux578 <notifications@github.com>:

**Comment by headswe** [comment]
I haven't seen this in ages.
