### ISSUE TITLE
Error Creating Repo (version 2.1.1.3)

### ISSUE THREAD

**Issue by firefly2442** [headswe/Swifty#113]
I get the following error when importing a URL or creating one from scratch:

```
2015-12-27 15:23:15,756 [6] INFO SwiftUpdater.Controls.NewRepoBox - Unable to translate bytes [D0] at index 13 from specified code page to Unicode.
System.Text.DecoderFallbackException: Unable to translate bytes [D0] at index 13 from specified code page to Unicode.
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes, Char*& chars)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.Convert(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at System.Text.DecoderNLS.Convert(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at NetSerializer.Primitives.ReadPrimitive(Stream stream, String& value) in h:\Development\C#\netserializer\NetSerializer\Primitives.cs:line 514
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at Deserialize(Serializer serializer, Stream stream, KeyValuePair`2[]& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at NetSerializer.DictionarySerializer.ReadPrimitive[TKey,TValue](Serializer serializer, Stream stream, Dictionary`2& value) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\DictionarySerializer.cs:line 162
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at Deserialize(Serializer serializer, Stream stream, KeyValuePair`2[]& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at NetSerializer.DictionarySerializer.ReadPrimitive[TKey,TValue](Serializer serializer, Stream stream, Dictionary`2& value) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\DictionarySerializer.cs:line 162
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at Deserialize(Serializer serializer, Stream stream, Addon& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at Deserialize(Serializer serializer, Stream stream, Addon[]& value)
   at Deserialize(Serializer serializer, Stream stream, List`1& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at Deserialize(Serializer serializer, Stream stream, RepoData& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob) in h:\Development\C#\netserializer\NetSerializer\TypeSerializers\ObjectSerializer.cs:line 72
   at SwiftUpdater.AddonNet.Deserialize(String repoPath) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 175
   at SwiftUpdater.AddonNet.GetChangesHttp() in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 240
   at SwiftUpdater.Controls.NewRepoBox.GetChanges_DoWork(Object sender, DoWorkEventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Controls\NewRepoBox.cs:line 167
```

**Comment by headswe** [comment]
Did you update the repo?

**Comment by firefly2442** [comment]
Well, I ran `patchcreator.exe -r modsfolder outputfolder`.  I'm assuming this overwrites and updates files accordingly?

**Comment by headswe** [comment]
Did you update patchcreator and various extras?.

**Comment by firefly2442** [comment]
I ran swifty and checked the settings page and it said it had updated to 2.1.1.3.  Is it better to run the uninstaller and then re-install from the setup application?  Thanks.

**Comment by Sniperhid** [comment]
As part of the update patchcreator was updated. You need to re-create the repository using the new version of patchcreator.exe

Are you sure this repository you are trying to added was with the latest version of patchcreator.exe ? We would appreciate if you could recreate it with the latest patchcreator.exe and try again, let us know how it goes!

**Comment by firefly2442** [comment]
Ah, my apologies.  I didn't notice that swifty upon update creates a new folder with the version number so I was running the old one.  Thank you for the help.
