### ISSUE TITLE
Swifty capitalizing files resulting in 404 error [2.1.2.1]

### ISSUE THREAD

**Issue by firefly2442** [headswe/Swifty#119]
Swifty [2.1.2.1] seems to be capitalizing some parts of files which then result in a 404 error upon download.  Here is an example from the ALIVE mod.

The original file from the mod:
```
ALIVE\demo\mp\alive_air_assault.altis\readme.txt
```
The .spd file that Swifty creates:
```
ALIVE\demo\mp\alive_air_assault.altis\README.txt_0.spd
```
This results in a 404 in the log:
```
2016-01-16 00:51:21,387 [5] INFO SwiftUpdater.Pages.Download - Starting download for demo\mp\alive_air_assault.altis\readme.txt_0.spd
2016-01-16 00:51:23,743 [1] INFO SwiftUpdater.Pages.Download - Crash
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
2016-01-16 00:51:23,746 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
```

**Comment by headswe** [comment]
Swifty never uppercases stuff, more likely the reverse is happening.

**Comment by firefly2442** [comment]
[2.1.2.2]
I think maybe there's some sort of conflict with Play with Six.  I used Play with Six to verify a mod.  This results in change to capitalization of some files in the mod.  However, it really shouldn't matter to Swifty i wouldn't think.  Then I used Swifty to generate the .spd files.  This then results in the change to capitalization that I mentioned above.  I tried not using Play with Six to verify the mod but I'm still getting an error:

```
2016-01-18 21:58:24,421 [16] INFO SwiftUpdater.Pages.Download - Checking Added- keys\ALiVE.bikey
2016-01-18 21:58:24,421 [16] INFO SwiftUpdater.Pages.Download - Missing Added- keys\ALiVE.bikey
2016-01-18 21:58:24,421 [16] INFO SwiftUpdater.Pages.Download - Starting download : 241 : Http
2016-01-18 21:58:24,427 [16] INFO SwiftUpdater.Pages.Download - Starting download for alive_logo.paa_0.spd
2016-01-18 21:58:24,431 [16] INFO SwiftUpdater.Pages.Download - Starting download for LICENSE.txt_0.spd
2016-01-18 21:58:26,071 [16] INFO SwiftUpdater.Pages.Download - Crash
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at SwiftUpdater.TeamspeakUtilities.CheckUserConfig(Repository repo) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\TeamspeakUtilities.cs:line 54
   at SwiftUpdater.Pages.Download.Worker_DoWork(Object sender, DoWorkEventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\Download.cs:line 356
2016-01-18 21:58:27,313 [1] INFO SwiftUpdater.Pages.Download - Crash
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
2016-01-18 21:58:27,314 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
```
I also tried uninstalling and reinstalling Swifty to see if it's some type of caching issue.
