### ISSUE TITLE
PBO data not matching

### ISSUE THREAD

**Issue by CaseMonster** [headswe/Swifty#138]
When updating the repo on a client, I get the error: "PBO data not matching".  I can manually delete the PBO file on the client and Swifty will go ahead and redownload, but it won't seem to delta patch any PBO's I've created.

I've tried using Eliteness, Mikero's MakePBO, and BIS Addon Builder to create the PBO.

I'm using Nginx on Server 2012r2 to host the repo.

Thanks

**Comment by CaseMonster** [comment]
2016-04-05 18:09:47,607 [14] INFO SwiftUpdater.Pages.Download - Crash
System.Exception: Pbo data not matching.
   at SwiftUpdater.Pages.Download.PackPbos(IEnumerable`1 changedPbos) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\Download.cs:line 270
   at SwiftUpdater.Pages.Download.Worker_DoWork(Object sender, DoWorkEventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\Download.cs:line 385

**Comment by headswe** [comment]
Interesting, is it just yours?

**Comment by CaseMonster** [comment]
No, every client attempting to sync the repo has the same issue.

I did find a workaround, if i delete the output folder before building/updating the repo, it seems to work every time without issue.

**Comment by headswe** [comment]
Sweet, i'm pretty sure i know where the bug is then, thanks.
