### ISSUE TITLE
Error: One or more errors occured

### ISSUE THREAD

**Issue by shimavitz** [headswe/Swifty#141]
When downloading a repo update, whilst Swifty was working with the PBOs it threw and error and now keeps giving Error: One or more errors occurred, when I try and run a repo update.

**Comment by headswe** [comment]
Please provide logs.
%appdata%/swifty/swifty.log

**Comment by ToasterBR** [comment]
Also, don´t update the repos with Arma 3 running...

**Comment by LeanderCouplez** [comment]
I'm getting the same error, and can't seem to understand what the logs are on about.

2016-05-26 19:35:30,653 [7] INFO SwiftUpdater.Controls.NewRepoBox - One or more errors occurred.
System.AggregateException: One or more errors occurred. ---> System.Exception: size is wrong
   at SwiftAddon.PboData..ctor(FileInfo info, DirectoryInfo source, String addonName) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\PboData.cs:line 31
   at SwiftAddon.Addon.GetData(FileInfo info, DirectoryInfo source, String addonName) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\Addon.cs:line 73
   at SwiftAddon.Addon..ctor(String path) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\Addon.cs:line 55
   at SwiftUpdater.AddonNet.<>c__DisplayClass7.<ProcessChanges>b__5(Addon serverAddon) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 282
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SwiftUpdater.AddonNet.ProcessChanges(RepoData data) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 289
   at SwiftUpdater.AddonNet.GetChangesHttp() in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 198
   at SwiftUpdater.Controls.NewRepoBox.GetChanges_DoWork(Object sender, DoWorkEventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Controls\NewRepoBox.cs:line 169
---> (Inner Exception #0) System.Exception: size is wrong
   at SwiftAddon.PboData..ctor(FileInfo info, DirectoryInfo source, String addonName) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\PboData.cs:line 31
   at SwiftAddon.Addon.GetData(FileInfo info, DirectoryInfo source, String addonName) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\Addon.cs:line 73
   at SwiftAddon.Addon..ctor(String path) in c:\Users\Sebastian\Documents\Visual Studio 2012\Projects\SwiftAddon\SwiftAddon\Addon.cs:line 55
   at SwiftUpdater.AddonNet.<>c__DisplayClass7.<ProcessChanges>b__5(Addon serverAddon) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\AddonNet.cs:line 282
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by headswe** [comment]
Likely caused by some sort of fudged pbo.

Could both of you post your mod lists?

**Comment by headswe** [comment]
Size is wrong can be caused by certain mission pbos.

**Comment by LeanderCouplez** [comment]
Apparently it was a problem on our end. Sorry for wasting your time.
