### ISSUE TITLE
2.1.3.3 Repo Issue

### ISSUE THREAD

**Issue by IceMan8104** [headswe/Swifty#147]
I've been getting this error which isn't allowing me to update my repo. When I launch the game without updating, it only launches with any external mods not the repo content. I've made sure I have enough space and all the folder paths worked perfectly fine before this recent Swifty update.

2016-06-10 23:14:13,697 [3] INFO SwiftUpdater.Controls.NewRepoBox - Unable to translate bytes [93] at index 25 from specified code page to Unicode.
System.Text.DecoderFallbackException: Unable to translate bytes [93] at index 25 from specified code page to Unicode.
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes, Char*& chars)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.Convert(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at System.Text.DecoderNLS.Convert(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32& bytesUsed, Int32& charsUsed, Boolean& completed)
   at NetSerializer.Primitives.ReadPrimitive(Stream stream, String& value)
   at Deserialize(Serializer serializer, Stream stream, String[]& value)
   at NetSerializer.ObjectSerializer.Deserialize(Serializer serializer, Stream stream, Object& ob)
   at SwiftUpdater.AddonNet.Deserialize(String repoPath)
   at SwiftUpdater.AddonNet.GetChangesHttp()
   at SwiftUpdater.Controls.NewRepoBox.GetChanges_DoWork(Object sender, DoWorkEventArgs e)

**Comment by headswe** [comment]
The repository needs to updated
