### ISSUE TITLE
2.1.3.4 Error

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#148]
> `2016-06-11 12:53:18,231 [1] INFO SwiftUpdater.Program - Swifty Started
2016-06-11 12:53:18,247 [1] INFO SwiftUpdater.Program - Fonts checked
2016-06-11 12:53:18,250 [1] INFO SwiftUpdater.Settings - Attempting to load settings file
2016-06-11 12:53:18,250 [1] INFO SwiftUpdater.Settings - Loading settings file
2016-06-11 12:53:18,309 [1] INFO SwiftUpdater.Pages.RepoView - Repoview shown
2016-06-11 12:53:18,311 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
2016-06-11 12:53:18,378 [1] INFO SwiftUpdater.Pages.Main - MainView Shown
2016-06-11 12:53:30,914 [1] INFO SwiftUpdater.Program - Swifty Started
2016-06-11 12:53:30,929 [1] INFO SwiftUpdater.Program - Fonts checked
2016-06-11 12:53:30,930 [1] INFO SwiftUpdater.Settings - Attempting to load settings file
2016-06-11 12:53:30,930 [1] INFO SwiftUpdater.Settings - Loading settings file
2016-06-11 12:53:30,970 [1] INFO SwiftUpdater.Pages.RepoView - Repoview shown
2016-06-11 12:53:30,972 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
2016-06-11 12:53:31,013 [1] INFO SwiftUpdater.Pages.Main - MainView Shown
2016-06-11 12:53:44,745 [6] INFO SwiftUpdater.Controls.NewRepoBox - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SwiftUpdater.AddonNet.ProcessChanges(RepoData data)
   at SwiftUpdater.AddonNet.GetChangesHttp()
   at SwiftUpdater.Controls.NewRepoBox.GetChanges_DoWork(Object sender, DoWorkEventArgs e)
`

The repository is updated with the 2.1.3.4 repo creator.

**Comment by System98** [comment]
I got the same issue on a different repo. Log entries are in german.

> 2016-06-11 12:43:16,167 [1] INFO SwiftUpdater.Program - Swifty Started
2016-06-11 12:43:16,181 [1] INFO SwiftUpdater.Program - Fonts checked
2016-06-11 12:43:16,181 [1] INFO SwiftUpdater.Settings - Attempting to load settings file
2016-06-11 12:43:16,182 [1] INFO SwiftUpdater.Settings - Loading settings file
2016-06-11 12:43:16,214 [1] INFO SwiftUpdater.Pages.RepoView - Repoview shown
2016-06-11 12:43:16,215 [1] INFO SwiftUpdater.Pages.RepoView - Updateing view
2016-06-11 12:43:16,255 [1] INFO SwiftUpdater.Pages.Main - MainView Shown
2016-06-11 12:43:21,261 [7] INFO SwiftUpdater.Controls.NewRepoBox - Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SwiftUpdater.AddonNet.ProcessChanges(RepoData data)
   bei SwiftUpdater.AddonNet.GetChangesHttp()
   bei SwiftUpdater.Controls.NewRepoBox.GetChanges_DoWork(Object sender, DoWorkEventArgs e)

**Comment by jonpas** [comment]
@System98 's repo was generated with the additional swifty-cli @headswe posted soon after 2.1.3.3, not with released 2.1.3.4.

**Comment by jonpas** [comment]
I have just confirmed that happens on released 2.1.3.4 as well.

**Comment by headswe** [comment]
Fixed in 05.
