### ISSUE TITLE
swifty-cli.exe: update fails with "Unhandled Exception: System.IO.DirectoryNotFoundException" - 2.1.3.7

### ISSUE THREAD

**Issue by curiousinternals** [headswe/Swifty#152]
I created a new swifty repo as follows:
```
$ swifty-cli.exe create sources/example targets/example
  ... etc ...
create finished with Sucess!
```

Next, I tried to update it (I hope I'm doing this right):
```
$ swifty-cli.exe update sources/example_updated targets/example
Running update...
Scanning @Advanced Sling Loading

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'p:\home\curiousinternals\swifty\sources\example_updated\sources\example_updated\@Advanced Sling Loading'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOpt
ion, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at swifty_cli.Update.NeedsUpdate(String repofolder, Addon addon, List`1 addonfolders)
   at swifty_cli.Update.Do(List`1 args)
   at swifty_cli.Program.Main(String[] args)
Signal 67
```

What's interesting is that part of the path appears to be doubled up:
```
sources\example_updated\sources\example_updated
```

**Comment by curiousinternals** [comment]
Workaround:

`.` is equivalent to `./.`

```
$ cd sources/example_updated
$ swifty-cli.exe update . ../../targets/example
```
