### ISSUE TITLE
Error when creating repository.

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#170]
When creating a repo with swifty-cli.exe, this error occurs:

C:\Users\Administrator\AppData\Local\Swifty\app-2.1.5\tools>swifty-cli.exe creat
e C:\SwiftyInputTest C:\SwiftyOutputTest
Processing @oly - 1/1

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
 System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)

   at SwiftAddon.FileData.ProcessPbo(FileStream stream)
   at SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String addo
nName)
   at SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass21`2.<ForEachWorker>b__17
(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b_
_10(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int
32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWit
hState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] ar
ray, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Act
ion`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEveryt
hing, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`
1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState
, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Act
ion`1 body)
   at SwiftAddon.Addon..ctor(String path)
   at swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   at swifty_cli.Create.Do(List`1 args)
   at swifty_cli.Program.Main(String[] args)

If it is of any help, I found the .pbo file that causes the error and uploaded it here: https://drive.google.com/open?id=0BxlsqxApTGGDY21PRW1Mb3hFdFE

**Comment by ryanparsons7** [comment]
Did abit more testing and found that 2 more files from the Mighty GAU-8 mod cause this issue also.
AlZab_mighty_gau8_ace_a10c.pbo
AlZab_mighty_gau8_avenger.pbo
AlZab_mighty_gau8_rhs_a10a.pbo

**Comment by headswe** [comment]
The pbos are missing their product entry.

I've fixed the parser for account for this, but there wont be a update until later today.

**Comment by headswe** [comment]
Fixed in 2.1.5.1
