### ISSUE TITLE
Crash when downloading

### ISSUE THREAD

**Issue by headswe** [headswe/Swifty#171]
``` Download for @cup_terrains\addons/cup_terrains_ca_data_baf.pbo.cup_terrains_core-1.3.0.bisign faulted with Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SwiftUpdater.Pages.NDownload.GetLabel()
   at SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)
2017-02-13 18:24:44,868 [14] INFO SwiftUpdater.Pages.NDownload - Download for @cup_terrains\addons/cup_terrains_ca_data.pbo faulted with Stack empty.
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at SwiftUpdater.Pages.NDownload.GetLabel()
   at SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)```

**Comment by headswe** [comment]
This is a symptom of an other exception.
