### ISSUE TITLE
Error when creating repository - mikero obsfucation

### ISSUE THREAD

**Issue by mikehudak** [headswe/Swifty#172]
When creating a repo with swifty-cli.exe, this error occurs:

```
Processing @fow - 1/1

Neosetrená vyjimka: System.AggregateException: Doslo k jedné nebo více chybám. -
--> System.ArgumentException: Polozka s tímto klícem jiz byla pridána.
   v System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   v System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Bool
ean add)
   v System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   v SwiftAddon.FileData.ProcessPbo(FileStream stream)
   v SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String addon
Name)
   v SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0
(Int32 i)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvoke()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>
b__0(Object )
   --- Konec trasování zásobníku pro vnitrní vyjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledE
xceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTok
en cancellationToken)
   v System.Threading.Tasks.Task.Wait()
   v System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int3
2 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWith
State, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] arr
ay, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Acti
on`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEveryth
ing, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1
 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState,
 Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEv
erything, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Acti
on`1 body)
   v SwiftAddon.Addon..ctor(String path)
   v swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   v swifty_cli.Create.Do(List`1 args)
   v swifty_cli.Program.Main(String[] args)
```

**Comment by Sniperhid** [comment]
I believe this is occurring because the repo generator is getting caught up on certain pbos. This is likely one of the pbos in the mod `@fow` - Is the Faces of War mod ( https://forums.bistudio.com/topic/198194-faces-of-war-ww2/ ) ?

**Comment by mikehudak** [comment]
@Sniperhid  Yes, it is @fow - Faces of War mod

**Comment by mikehudak** [comment]
Still issue also in 2.1.5.2

**Comment by mikehudak** [comment]
Still issue in 2.1.5.5

```
Processing @FOW - 1/1

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SwiftAddon.FileData.ProcessPbo(FileStream stream)
   at SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String addonName)
   at SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SwiftAddon.Addon..ctor(String path)
   at swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   at swifty_cli.Create.Do(List`1 args)
   at swifty_cli.Program.Main(String[] args)
```

**Comment by mikehudak** [comment]
https://www.youtube.com/watch?v=GTN_WzdObSY

**Comment by headswe** [comment]
I intend to investigate this in the weekend.

**Comment by mikehudak** [comment]
Any findings ?

**Comment by headswe** [comment]
I just ran trough FOW and managed to crunch it fine using swifty cmd create.

**Comment by mikehudak** [comment]
Just tested on clean installation of windows with 2.1.5.6

![fow_error](https://cloud.githubusercontent.com/assets/1401860/23671188/a6ee041a-036a-11e7-9155-9308a2660551.png)

Download mod from: https://forums.bistudio.com/topic/198194-faces-of-war-ww2
mega / google drive link

**Comment by headswe** [comment]
Having toyed with this a bit more, i managed to solve one of the errors due to their usage of files with same name but capitalized different, but sadly they somehow managed to cram two identical named files into a pbo and this causes the error.

For now i suggest turning to the source of the issue and il try to work around this issue by disabling pbo delta patching on it.

**Comment by mikehudak** [comment]
New addon have same problem. Processing addon @csa38 is resulting with same issue. 
Here is link to mod:  http://www.moddb.com/mods/csa38-czechoslovak-army-1938

**Comment by headswe** [comment]
They also use mikero obsfucation

**Comment by mikehudak** [comment]
Resolved with new config

`"disablepbodeltapatching=@fow,@csa_38"`
