### ISSUE TITLE
One or more files were not downloaded

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#184]
Quite a few from my group are getting this error when downloading files.

![unknown](https://cloud.githubusercontent.com/assets/13571100/23322226/dd858d42-fada-11e6-98d5-aa7740b71f3c.png)

Here's the log from the user:
[Swifty.txt](https://github.com/headswe/Swifty/files/800535/Swifty.txt)

I'm wondering if this is an issue on my server's end when managing connections or swifty?

Thanks.

**Comment by headswe** [comment]
This issued is caused by temp files, there is a issue currently where files are not cleaned up correctly.

System.IO.IOException: Cannot create "C:\Users\Admin\AppData\Roaming\Swifty\temp\Olympus\@CUPTerrain\Addons\cup_terrains_cwa_plants.pbo" because a file or directory with the same name already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

Deleting the folder Olympus at C:\Users\Admin\AppData\Roaming\Swifty\temp should solve this error.

**Comment by ryanparsons7** [comment]
Hi, he tried that and still got the same error. Here's a snippet from his log file showing the exact errors hes getting at that time:

2017-02-24 22:45:25,433 [22] INFO SwiftUpdater.Pages.NDownload - Download for @cupterrain\addons\cup_terrains_ca_wheeled2_dummy.pbo faulted with The underlying connection was closed: The connection was closed unexpectedly.
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)
2017-02-24 22:45:25,442 [21] INFO SwiftUpdater.Pages.NDownload - Download for @cupterrain\addons\cup_terrains_cwa_buildings_c.pbo faulted with Stack empty.
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at SwiftUpdater.Pages.NDownload.GetLabel()
   at SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)

**Comment by headswe** [comment]
The underlying connection was closed: The connection was closed unexpectedly. is a server issue..

Perhaps throttling from the webserver.

**Comment by ryanparsons7** [comment]
I was suspecting that.

I'm running the webserver through the latest stack of XAMPP with Apache 2.4.25

How would I go around removing the throttle or figuring out what would be causing this?

Thanks so much.

**Comment by jonpas** [comment]
XAMPP is a development environment, I would really not recommend running that stack for a public server, it has a bunch of development stuff enabled that can be vulnerable and expose your server unnecessarily.
