### ISSUE TITLE
Download faulted with Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#188]
One of our group members continues to get this error, he has repeatedly deleted the temp files to no avail. 

2017-03-04 02:52:15,514 [27] INFO SwiftUpdater.Pages.NDownload - Download for @cupterrain\addons\cup_terrains_ca_buildings2.pbo faulted with Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SwiftUpdater.Pages.NDownload.GetLabel()
   at SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)

**Comment by headswe** [comment]
I need a full unedited log.

**Comment by ryanparsons7** [comment]
[Swifty.txt](https://github.com/headswe/Swifty/files/818635/Swifty.txt)

**Comment by ketonan** [comment]
Same errors here with version 2.1.5.8.
Deleting "Temporary download folder" and "Roaming\Swifty\Cache" folder contect sometimes fix the issue.
This happens when updating mods, new downloads/mods works ok. This just happened to use with new CUP update.
Here's log:
[Swifty2.txt](https://github.com/headswe/Swifty/files/918715/Swifty2.txt)

**Comment by headswe** [comment]
Fixed in 2.1.7
