### ISSUE TITLE
update-forced no longer works in 2.1.5.7

### ISSUE THREAD

**Issue by kerckasha** [headswe/Swifty#197]
Errors out with:
Happens regardless of number of folders 

```
Running update...

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at swifty_cli.UpdateForced.Do(List`1 args)
   at swifty_cli.Program.Main(String[] args)
```

**Comment by headswe** [comment]
Fixed in the next version.
