### ISSUE TITLE
Updater fails, object reference not set to an instance of an object

### ISSUE THREAD

**Issue by kerckasha** [headswe/Swifty#94]
After updating repo to the newest version it would fail upon updating. It seemed to only happen with a particular addon (in-house combination mod folder of smaller mods) but there was no issue with the previous version.

2015-12-04 03:00:42,324 [15] INFO SwiftUpdater.Pages.Download - Starting download : 0 : Http
2015-12-04 03:00:42,331 [15] INFO SwiftUpdater.Pages.Download - Crash
System.NullReferenceException: Object reference not set to an instance of an object.
   at SwiftUpdater.Pages.Download.GetTempPath(FileData data)
   at SwiftUpdater.Pages.Download.Patch()
   at SwiftUpdater.Pages.Download.Work()
   at SwiftUpdater.Pages.Download.Worker_DoWork(Object sender, DoWorkEventArgs e)
was the error in the log file, it would download all the files required to do the update and fail when it started to apply the changes. deleting the mods and redownloading didn't solve anything

**Comment by headswe** [comment]
I would need the mod in question to look at.

**Comment by headswe** [comment]
I found this the other day, caused by a improper cast.

It's fixed!.
