### ISSUE TITLE
Patchcreator error

### ISSUE THREAD

**Issue by nikolauska** [headswe/Swifty#96]
#### Swifty version
2.1.1.0

#### Patchcreator version
0.0.0.8 

#### Description
This error came up when trying to update repository with patchcreator

#### Error message
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at SwiftAddon.AddonExporter.ExportPbo(PboData data, String outpath, Byte[] bu
ffer)
   at SwiftAddon.AddonExporter.Export(CommonData file, String outpath, Byte[] bu
ffer)
   at SwiftAddon.AddonExporter.<>c__DisplayClass3.<ExportDataFiles>b__2(Addon ad
don)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass2d`2.<ForEachWorker>b__23
(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b_
_10(Object param0)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int
32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWit
hState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list
, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action
`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverythin
g, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`
1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState
, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Act
ion`1 body)
   at SwiftAddon.AddonExporter.ExportDataFiles(String outpath)
   at PatchCreatorCMD.Program.Main(String[] args)
```

**Comment by nikolauska** [comment]
After debugging we noticed this error comes up when repository contains empty files. After cleaning those the patchcreator doesn't give any errors.

**Comment by headswe** [comment]
One of your pbo contains zero files.

**Comment by headswe** [comment]
Error caused by empty pbo.
